apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 30
    failureThreshold: 10
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 200m
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad
    outbound:
      external:
        - host: familie-ba-mottak.prod-fss-pub.nais.io
        - host: api-gw.oera.no
        - host: login.microsoftonline.com
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/apigw/prod/kodeverk.rest-api/familie-ba-soknad-api
        mountPath: /secret/apikeys/kodeverk-api-key
  env:
    - name: APP_TEAM
      value: teamfamilie
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: ba-soknad-api
    - configmap: loginservice-idporten
