FAMILIE_BA_MOTTAK_URL: http://localhost:8090
PDL_API_URL: http://localhost:1337/rest/api/pdl
KODEVERK_URL: #Mockes lokalt

PDL_API_APIKEY: test-apikey
MOTTAK_APIKEY: test-apikey
STS_APIKEY: test-apikey
KODEVERK_APIKEY: test-apikey

no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

CREDENTIAL_USERNAME: dummy
CREDENTIAL_PASSWORD: dummy
