no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    accepted_audience: ${ACCEPTEDAUDIENCE}
    cookie_name: selvbetjening-idtoken

FAMILIE_BA_MOTTAK_URL: https://familie-ba-mottak.prod-fss-pub.nais.io
PDL_API_URL: https://api-gw.oera.no/pdl-api
STS_URL: https://api-gw.oera.no/security-token-service
