application.name: familie-ba-soknad-api

server:
  servlet:
    context-path: /
  port: 8080

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true

FAMILIE_BA_MOTTAK_URL: https://familie-ba-mottak.dev-fss-pub.nais.io
PDL_API_URL: https://api-gw-q1.oera.no/pdl-api
