no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    cookie_name: selvbetjening-idtoken

FAMILIE_BA_MOTTAK_URL: https://api-gw.oera.no/familie-ba-mottak
PDL_API_URL: https://api-gw.oera.no/pdl-api
STS_URL: https://api-gw.oera.no/security-token-service/rest/v1/sts/token
