FAMILIE_BA_MOTTAK_URL: http://localhost:8090
PDL_API_URL: http://familie-mock-server:1337

PDL_API_APIKEY: #secret

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"